version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  web:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
      args:
        RUBY_VERSION: ${RUBY_VERSION}
        RAILS_APP_NAME: ${RAILS_APP_NAME}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    command: bundle exec rails s -p ${RAILS_PORT} -b '0.0.0.0'
    volumes:
      - ./${RAILS_APP_NAME}:/${RAILS_APP_NAME}
    ports:
      - "${RAILS_PORT}:${RAILS_PORT}"
    depends_on:
      - db