default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: 5

development:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>_development

test:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>_test

production:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>_production